# ------------------------------------------------
# |          Clash Config Make by O7Y0           |
# |     TG Channel: https://t.me/REBIRTHOKAY     |
# |       GitHub: https://github.com/O7Y0        |
# |          Update Date: 2022.10.20             |
# |                  enjoy                       |
# ------------------------------------------------
mixed-port: 7890 # æœ¬åœ°æ··åˆä»£ç†ç«¯å£[http+socks5]
allow-lan: true # å…è®¸å±€åŸŸç½‘è¿æ¥[false/true]
bind-address: '*'
  # ç›‘å¬IPç™½åå•[å½“allow-lanï¼štrue],åªå…è®¸åˆ—è¡¨è®¾å¤‡
  # '*'å…¨éƒ¨è®¾å¤‡
  # 192.168.122.11
  # å•ä¸ªip4åœ°å€
  # "[aaaa::a8aa:ff:fe09:57d8]"
  # å•ä¸ªip6åœ°å€
mode: rule # clashå·¥ä½œæ¨¡å¼[rule|global|direct]
ipv6: true
log-level: info # æ—¥å¿—ç­‰çº§[info|warning|error|debug|silent]
external-controller: 127.0.0.1:9090 # æ§åˆ¶å™¨ç›‘å¬åœ°å€
secret: 
dns:
  enable: true # DNSå¼€å…³[false|true]
  listen: 0.0.0.0:53 # DNSç›‘å¬åœ°å€
  ipv6: false # IP6è§£æå¼€å…³ï¼›å¦‚æœä¸ºfalseï¼Œå°†è¿”å›ip6ç»“æœä¸ºç©º
  default-nameserver:
    # è§£æéIPçš„dnsç”¨çš„dnsæœåŠ¡å™¨,åªæ”¯æŒçº¯IP
    - 1.1.1.1
    - 119.29.29.29
  enhanced-mode: fake-ip # DNSæ¨¡å¼[redir-host|fake-ip]
  fake-ip-range: 198.18.0.1/16 # Fake-IPè§£æåœ°å€æ± 
  fake-ip-filter:
    # Fake-ipè¿‡æ»¤ï¼Œåˆ—è¡¨ä¸­çš„åŸŸåè¿”å›çœŸå®ip
    # Local Area Network
    - '*.lan'
    # Stun Services
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - '+.stun.*.*.*.*'
    - '+.stun.*.*.*.*.*'
    # Google Voices
    - 'lens.l.google.com'
    # Nintendo Switch
    - '*.n.n.srv.nintendo.net'
    # PlayStation
    - '+.stun.playstation.net'
    # XBox
    - 'xbox.*.*.microsoft.com'
    - '*.*.xboxlive.com'
    # Microsoft
    - '*.msftncsi.com'
    - '*.msftconnecttest.com'
    # Bilibili CDN
    - '*.mcdn.bilivideo.cn'
  nameserver:
    # é»˜è®¤DNSæœåŠ¡å™¨ï¼Œæ”¯æŒudp/tcp/dot/doh/doq
    - https://dns.pub/dns-query
    - https://223.6.6.6/dns-query
    - https://rubyfish.cn/dns-query

proxies: # æœ¬åœ°æœåŠ¡å™¨
proxy-providers:
  sub1:
    #æ”¹sub1é¡¹ç›®å
    type: http
    url: 
    #æ”¹è®¢é˜…é“¾æ¥
    interval: 3600
    path: ./profiles/sub1.yaml
    #é€‰ä¸€ä¸ªè‡ªå·±å–œæ¬¢çš„åå­—æ”¹æ‰sub2ç­‰å…³é”®è¯
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

  sub2:
    type: http
    url: 
    interval: 3600
    path: ./profiles/sub2.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

proxy-groups:
  - name: è‡ªåŠ¨é€‰æ‹©
    type: url-test
    use:
      - sub1
      - sub2
    url: "http://www.gstatic.com/generate_204"
    interval: 300

  - name: æ‰‹åŠ¨åˆ‡æ¢
    type: select
    use:
      - sub1
      - sub2
    proxies:
      - è‡ªåŠ¨é€‰æ‹©
      
  - name: OpenAI
    type: select
    proxies:
      - æ‰‹åŠ¨åˆ‡æ¢
      - è‡ªåŠ¨é€‰æ‹©
      - DIRECT
      - æ—¥æœ¬èŠ‚ç‚¹
      - ç¾å›½èŠ‚ç‚¹
      - æ–°åŠ å¡èŠ‚ç‚¹

  - name: è°·æ­ŒæœåŠ¡
    type: select
    proxies:
      - æ‰‹åŠ¨åˆ‡æ¢
      - è‡ªåŠ¨é€‰æ‹©
      - DIRECT
      - é¦™æ¸¯èŠ‚ç‚¹
      - å°æ¹¾èŠ‚ç‚¹
      - æ—¥æœ¬èŠ‚ç‚¹
      - ç¾å›½èŠ‚ç‚¹
      - æ–°åŠ å¡èŠ‚ç‚¹

  - name: æ²¹ç®¡æœåŠ¡
    type: select
    proxies:
      - è‡ªåŠ¨é€‰æ‹©
      - æ‰‹åŠ¨åˆ‡æ¢
      - DIRECT
      - é¦™æ¸¯èŠ‚ç‚¹
      - å°æ¹¾èŠ‚ç‚¹
      - æ—¥æœ¬èŠ‚ç‚¹
      - ç¾å›½èŠ‚ç‚¹
      - æ–°åŠ å¡èŠ‚ç‚¹

  - name: ç”µæŠ¥æœåŠ¡
    type: select
    proxies:
      - è‡ªåŠ¨é€‰æ‹©
      - æ‰‹åŠ¨åˆ‡æ¢
      - DIRECT
      - é¦™æ¸¯èŠ‚ç‚¹
      - å°æ¹¾èŠ‚ç‚¹
      - æ—¥æœ¬èŠ‚ç‚¹
      - ç¾å›½èŠ‚ç‚¹
      - æ–°åŠ å¡èŠ‚ç‚¹

  - name: ç§å­ç½‘ç«™
    type: select
    proxies:
      - DIRECT
      - æ‰‹åŠ¨åˆ‡æ¢
      - è‡ªåŠ¨é€‰æ‹©
      - é¦™æ¸¯èŠ‚ç‚¹
      - å°æ¹¾èŠ‚ç‚¹
      - æ—¥æœ¬èŠ‚ç‚¹
      - ç¾å›½èŠ‚ç‚¹
      - æ–°åŠ å¡èŠ‚ç‚¹

  - name: å¹¿å‘Šå±è”½
    type: select
    proxies:
      - REJECT
      - æ‰‹åŠ¨åˆ‡æ¢

  - name: è‹¹æœæœåŠ¡
    type: select
    proxies:
      - DIRECT
      - æ‰‹åŠ¨åˆ‡æ¢
      - è‡ªåŠ¨é€‰æ‹©
      - é¦™æ¸¯èŠ‚ç‚¹
      - å°æ¹¾èŠ‚ç‚¹
      - æ—¥æœ¬èŠ‚ç‚¹
      - ç¾å›½èŠ‚ç‚¹
      - æ–°åŠ å¡èŠ‚ç‚¹

  - name: å¾®è½¯æœåŠ¡
    type: select
    proxies:
      - DIRECT
      - æ‰‹åŠ¨åˆ‡æ¢
      - è‡ªåŠ¨é€‰æ‹©
      - é¦™æ¸¯èŠ‚ç‚¹
      - å°æ¹¾èŠ‚ç‚¹
      - æ—¥æœ¬èŠ‚ç‚¹
      - ç¾å›½èŠ‚ç‚¹
      - æ–°åŠ å¡èŠ‚ç‚¹

  - name: å…¨çƒåŠ é€Ÿ
    type: select
    proxies:
      - è‡ªåŠ¨é€‰æ‹©
      - æ‰‹åŠ¨åˆ‡æ¢
      - DIRECT
      - é¦™æ¸¯èŠ‚ç‚¹
      - å°æ¹¾èŠ‚ç‚¹
      - æ—¥æœ¬èŠ‚ç‚¹
      - ç¾å›½èŠ‚ç‚¹
      - æ–°åŠ å¡èŠ‚ç‚¹

  - name: å›½å†…ç½‘ç«™
    type: select
    proxies:
      - DIRECT
      - æ‰‹åŠ¨åˆ‡æ¢
      - è‡ªåŠ¨é€‰æ‹©
      - é¦™æ¸¯èŠ‚ç‚¹
      - å°æ¹¾èŠ‚ç‚¹
      - æ—¥æœ¬èŠ‚ç‚¹
      - ç¾å›½èŠ‚ç‚¹
      - æ–°åŠ å¡èŠ‚ç‚¹
      
  - name: é»‘ç™½åå•
    type: select
    proxies:
      - DIRECT
      - è‡ªåŠ¨é€‰æ‹©
      - æ‰‹åŠ¨åˆ‡æ¢
      - é¦™æ¸¯èŠ‚ç‚¹
      - å°æ¹¾èŠ‚ç‚¹
      - æ—¥æœ¬èŠ‚ç‚¹
      - ç¾å›½èŠ‚ç‚¹
      - æ–°åŠ å¡èŠ‚ç‚¹

  - name: é¦™æ¸¯èŠ‚ç‚¹
    type: url-test
    use:
      - sub1
      - sub2
    tolerance: 30
    lazy: true
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    filter: 'ğŸ‡­ğŸ‡°|HK|é¦™æ¸¯'
    strategy: consistent-hashing

  - name: å°æ¹¾èŠ‚ç‚¹
    type: url-test
    use:
      - sub1
      - sub2
    tolerance: 30
    lazy: true
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    # disable-udp: true
    filter: 'å°|TW'
    strategy: consistent-hashing

  - name: æ—¥æœ¬èŠ‚ç‚¹
    type: url-test
    use:
      - sub1
      - sub2
    tolerance: 30
    lazy: true
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    # disable-udp: true
    filter: 'æ—¥|JP|ğŸ‡¯ğŸ‡µ'
    strategy: consistent-hashing

  - name: ç¾å›½èŠ‚ç‚¹
    type: url-test
    use:
      - sub1
      - sub2
    tolerance: 30
    lazy: true
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    # disable-udp: true
    filter: 'ç¾|US|ğŸ‡ºğŸ‡¸'
    strategy: consistent-hashing

  - name: æ–°åŠ å¡èŠ‚ç‚¹
    type: url-test
    use:
      - sub1
      - sub2
    tolerance: 30
    lazy: true
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    # disable-udp: true
    filter: 'æ–°|å¡|SG|ğŸ‡¸ğŸ‡¬'
    strategy: consistent-hashing

rule-providers:
  # è¿œç¨‹è§„åˆ™é›†
  Direct:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@release/rule/Clash/Direct/Direct.yaml"
    path: ./ruleset/direct.yaml
    interval: 86400

  adblock:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@release/rule/Clash/AdvertisingLite/AdvertisingLite.yaml"
    path: ./ruleset/Advertising_Classical.yaml
    interval: 86400
    
  OpenAI:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@release/rule/Clash/OpenAI/OpenAI.yaml"
    path: ./ruleset/Google.yaml
    interval: 86400
    
  Google:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@release/rule/Clash/Google/Google.yaml"
    path: ./ruleset/Google.yaml
    interval: 86400

  YouTube:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@release/rule/Clash/YouTube/YouTube.yaml"
    path: ./ruleset/YouTube.yaml
    interval: 86400

  Telegram:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@release/rule/Clash/Telegram/Telegram.yaml"
    path: ./ruleset/Telegram.yaml
    interval: 86400

  PrivateTracker:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/O7Y0/Profiles@master/Clash/PrivateTracker.yaml"
    path: ./ruleset/PrivateTracker.yaml
    interval: 86400

  Apple:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@release/rule/Clash/Apple/Apple.yaml"
    path: ./ruleset/Apple.yaml
    interval: 86400

  Microsoft:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@release/rule/Clash/Microsoft/Microsoft.yaml"
    path: ./ruleset/Microsoft.yaml
    interval: 86400

  China:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@release/rule/Clash/China/China.yaml"
    path: ./ruleset/China.yaml
    interval: 86400
    
  Global_Classical:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@release/rule/Clash/Global/Global_Classical.yaml"
    path: ./ruleset/Global_Classical.yaml
    interval: 86400

rules:
  - DOMAIN-SUFFIX,openai.com,OpenAI
  - DOMAIN-SUFFIX,fsm.name,å…¨çƒåŠ é€Ÿ
  - DOMAIN-SUFFIX,zhuque.in,å…¨çƒåŠ é€Ÿ
  - DOMAIN-SUFFIX,u2.dmhy.org,å…¨çƒåŠ é€Ÿ
  - DOMAIN-SUFFIX,deepl.com,å…¨çƒåŠ é€Ÿ
  - DOMAIN-SUFFIX,mozilla.org,å…¨çƒåŠ é€Ÿ
  - RULE-SET,Direct,DIRECT
  - RULE-SET,adblock,å¹¿å‘Šå±è”½
  - RULE-SET,OpenAI,OpenAI
  - RULE-SET,Google,è°·æ­ŒæœåŠ¡
  - RULE-SET,YouTube,æ²¹ç®¡æœåŠ¡
  - RULE-SET,Telegram,ç”µæŠ¥æœåŠ¡
  - RULE-SET,PrivateTracker,ç§å­ç½‘ç«™
  - RULE-SET,Apple,è‹¹æœæœåŠ¡
  - RULE-SET,Microsoft,å¾®è½¯æœåŠ¡
  - RULE-SET,China,å›½å†…ç½‘ç«™
  - RULE-SET,Global_Classical,å…¨çƒåŠ é€Ÿ
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,100.64.0.0/10,DIRECT
  - IP-CIDR,224.0.0.0/4,DIRECT
  - IP-CIDR,fe80::/10,DIRECT
  - IP-CIDR,119.28.28.28/32,DIRECT
  - IP-CIDR,182.254.116.0/24,DIRECT
  - GEOIP,CN,å›½å†…ç½‘ç«™
  - MATCH,é»‘ç™½åå•
